name: "frontend default workflow"

permissions:
  contents: write
  pull-requests: write
  id-token: write
  issues: write

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  merge_group:
    branches: [main, develop]
jobs:
  # maps the branch to an environment and sets it as output for the rest of the workflow
  set-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.map-branch-to-env.outputs.environment }}

    steps:
      - id: map-branch-to-env
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "environment=dev" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "environment=int" >> "$GITHUB_OUTPUT"
          else
            echo "unable to set environment for ref ${GITHUB_REF}"
          fi
  # resolves environment specific variables like s3 bucket name or cloudfront distribution id and sets them as output for the rest of the workflow.
  # this is only needed if the variables are not used directly but instead passed as input to a subworkflow
  resolve-env-vars:
    runs-on: ubuntu-latest
    needs: set-env
    environment:  ${{ needs.set-env.outputs.environment }}
    outputs:
      frontend_s3_bucket: ${{ steps.out.outputs.frontend_s3_bucket }}
      cloudfront_distribution_id: ${{ steps.out.outputs.cloudfront_distribution_id }}
      aws_region: ${{ steps.out.outputs.aws_region }}
    steps:
      - id: out
        run: |
          echo "resolving environment specific variables for environment ${{ needs.set-env.outputs.environment }}"
          echo "frontend_s3_bucket=${{ vars.FRONTEND_S3_BUCKET }}"
          echo "frontend_s3_bucket=${{ vars.FRONTEND_S3_BUCKET }}" >> "$GITHUB_OUTPUT"
          echo "cloudfront_distribution_id=${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}"
          echo "cloudfront_distribution_id=${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}" >> "$GITHUB_OUTPUT"

  frontend-workflow:
    name: '.'
    uses: blw-ofag-ufag/atlas-code-github-workflows/.github/workflows/frontend_workflow.yml@v1.0.0
    needs: [set-env, resolve-env-vars]
    secrets:
      SEMVER_PRIVATE_KEY: ${{ secrets.SEMVER_PRIVATE_KEY }}
      GH_ORG_GITLEAKS_PRIVATE_KEY: ${{ secrets.GH_ORG_GITLEAKS_PRIVATE_KEY }}
      LICENSE_KEY_GITLEAKS: ${{ secrets.LICENSE_KEY_GITLEAKS }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
      AWS_DEPLOYMENT_ROLE_ARN: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
    with:
      environment: ${{ needs.set-env.outputs.environment }}
      app-id: ${{ vars.GH_ORG_APP_ID }}
      gitleaks-app-id: ${{ vars.GH_ORG_GITLEAKS_APP_ID }}
      aws-region: ${{ vars.AWS_REGION }}
      frontend-s3-bucket: ${{ needs.resolve-env-vars.outputs.frontend_s3_bucket }}
      cloudfront-distribution-id: ${{ needs.resolve-env-vars.outputs.cloudfront_distribution_id }}
