name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: ./.github/workflows/release-please.yml
    with:
      release-type: simple
      target-branch: main
      app-id: ${{ vars.GH_ORG_APP_ID }}
    secrets:
      GH_ORG_PRIVATE_KEY: ${{ secrets.GH_ORG_PRIVATE_KEY }}