name: "frontend workflow that scans for secrets, vulnerabilities and code quality issues, creates a release and deploys to s3 (if the push was on main or develop)"
run-name: "frontend workflow for environment: ${{ inputs.environment }}"
permissions:
  contents: write
  pull-requests: write
  id-token: write
  issues: write

on:
  workflow_call:
    inputs:
      app-id:
        description: "GitHub App ID used for downstream workflows (like semantic versioning), must have write permissions to the repo"
        required: true
        type: string
      gitleaks-app-id:
        description: "GitHub App ID used by gitleaks to authenticate with the GitHub API (must have read permissions to the repo and prs"
        required: true
        type: string
      aws-region:
        description: "AWS region for deployment"
        required: true
        type: string
      frontend-s3-bucket:
        description: "S3 bucket name for frontend deployment"
        required: true
        type: string
      environment:
        description: "Deployment environment used to resolve secrets (e.g., dev, int)"
        required: true
        type: string
      enable-build-push:
        description: 'Enable build and publish to S3'
        required: false
        default: true
        type: boolean
      enable-infrastructure-update:
        description: 'Enable infrastructure update'
        required: false
        default: true
        type: boolean
      deployment-app-id:
        description: "GitHub App ID used for deployment authentication, must have permissions to create PRs on the infrastructure repository"
        required: true
        type: string
      application-name:
        description: "Name of the application being deployed, used to identify the correct infrastructure as code variable to update in the infrastructure repository (updates <application-name>_version)"
        required: true
        type: string
      github-organization:
        description: 'GitHub organization that owns the infrastructure repository'
        required: true
        type: string
      infrastructure_repo:
        description: 'Name Infrastructure repository'
        required: true
        type: string
      infrastructure_base_branch:
        description: 'Base branch for PR'
        required: false
        default: 'main'
        type: string
    secrets:
      SEMVER_PRIVATE_KEY:
        description: "GitHub App private key matching the app-id inputs"
        required: true
      GH_ORG_GITLEAKS_PRIVATE_KEY:
        description: "GitHub App private key matching the gitleaks-app-id input, used for gitleaks authentication"
        required: true
      LICENSE_KEY_GITLEAKS:
        description: "Gitleaks license key"
        required: true
      SONAR_TOKEN:
        description: "SonarQube authentication token"
        required: true
      AWS_OIDC_ROLE_ARN:
        description: "OIDC role ARN for AWS credentials"
        required: true
      AWS_DEPLOYMENT_ROLE_ARN:
        description: "Deployment role ARN for AWS credentials"
        required: true
      DEPLOYMENT_APP_PRIVATE_KEY:
        description: "GitHub App private key matching the deployment-app-id input, used for deployment authentication and creating PRs on the infrastructure repository"
        required: true

jobs:
  gitleaks:
    name: '.'
    uses: ./.github/workflows/gitleaks.yml
    secrets:
      GH_ORG_GITLEAKS_PRIVATE_KEY: ${{ secrets.GH_ORG_GITLEAKS_PRIVATE_KEY }}
      LICENSE_KEY_GITLEAKS: ${{ secrets.LICENSE_KEY_GITLEAKS }}
    with:
      gitleaks-app-id: ${{ inputs.gitleaks-app-id }}

  pnpm-audit:
    name: '.'
    uses: ./.github/workflows/node_pnpm_audit.yml
    with:
      prod: true
      audit-level: high

  trivy-scan:
    name: "."
    uses: ./.github/workflows/trivy_scan.yml

  unit-test-sonarqube:
    name: '.'
    uses: ./.github/workflows/node_sonarqube.yml
    needs: [ gitleaks, pnpm-audit, trivy-scan]
    with:
      run-lint: true
      run-tests: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  semantic-release:
    name: '.'
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') }}
    uses: ./.github/workflows/semantic_release.yml
    needs: [ unit-test-sonarqube, gitleaks, pnpm-audit, trivy-scan ]
    secrets:
      SEMVER_PRIVATE_KEY: ${{ secrets.SEMVER_PRIVATE_KEY }}
    with:
      app-id: ${{ inputs.app-id }}

  build-and-push:
    name: '.'
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') }}
    uses: ./.github/workflows/frontend_build_deploy_s3.yml
    needs: [ semantic-release ]
    secrets:
      AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
      AWS_DEPLOYMENT_ROLE_ARN: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
    with:
      enable: ${{ inputs.enable-build-push }}
      environment: ${{ inputs.environment }}
      build-configuration: ${{ github.ref == 'refs/heads/develop' && 'dev' || 'int' }}
      version: ${{needs.semantic-release.outputs.version }}
      aws-region: ${{ inputs.aws-region }}
      frontend-s3-bucket: ${{ inputs.frontend-s3-bucket }}

  update-infrastructure:
    name: Update Infrastructure
    needs: [ semantic-release, build-and-push ]
    if: needs.build-and-push.result == 'success'
    uses: ./.github/workflows/update_infrastructure.yml
    with:
      enable: ${{ inputs.enable-infrastructure-update }}
      image_tag: ${{ needs.semantic-release.outputs.version }}
      application_name: ${{ inputs.application-name }}
      infrastructure_repo: ${{ inputs.infrastructure_repo }}
      tfvars_path: 'terraform/terraform.auto.tfvars.json'
      base_branch: ${{ inputs.infrastructure_base_branch }}
      app-id: ${{ inputs.deployment-app-id }}
      github-organization: ${{ inputs.github-organization }}
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_APP_PRIVATE_KEY }}

  merge-main-develop:
    name: '.'
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/merge_main_develop.yml
    needs: [ semantic-release ]
    secrets:
      SEMVER_PRIVATE_KEY: ${{ secrets.SEMVER_PRIVATE_KEY }}
    with:
      app-id: ${{ inputs.app-id }}
