name: Release atlas code workflows
permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  merge_group:
    branches: [main]

jobs:
  gitleaks:
    name: '.'
    uses: ./.github/workflows/gitleaks.yml
    secrets:
      GH_ORG_GITLEAKS_PRIVATE_KEY: ${{ secrets.GH_ORG_GITLEAKS_PRIVATE_KEY }}
      LICENSE_KEY_GITLEAKS: ${{ secrets.LICENSE_KEY_GITLEAKS }}
    with:
      gitleaks-app-id: ${{ vars.GH_ORG_GITLEAKS_APP_ID }}

  release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/release-please.yml
    with:
      release-type: simple
      target-branch: main
      app-id: ${{ vars.GH_ORG_APP_ID }}
    secrets:
      GH_ORG_PRIVATE_KEY: ${{ secrets.GH_ORG_PRIVATE_KEY }}