permissions:
  contents: read

on:
  workflow_call:

jobs:
  vulnrability-scan:
    name: Check for vulnerabilities
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

#       --- Build only necessary if you want to detect build-time vulnerabilities (e.g. in webpack plugins) or if you want to do a full audit (instead of prod-only) ----
#      - name: Install dependencies
#        run: pnpm install --frozen-lockfile
#      - name: build application
#        run: pnpm build

      # ---- pnpm audit gate (detects more npm specific issues) ----
      - name: pnpm audit (prod, high+)
        run: pnpm audit --prod --audit-level=high

      # ---- Trivy scans ----
      - name: Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: table
          exit-code: 1

#     # todo upload SARIF to GitHub Security (probably needs advanced security activated on github repo, but costs a lot if repo is private, probably free once it is public), note also needs format to be sarif and not table
#      - name: Upload SARIF to GitHub Security
#        if: always()
#        uses: github/codeql-action/upload-sarif@v3
#        with:
#          sarif_file: trivy-results.sarif

      - name: Trivy (secrets) -> table
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          scanners: secret
          format: table
          exit-code: 1
